# Generated by Django 4.0.6 on 2022-07-30 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_now_add=True, verbose_name='is_created')),
                ('is_updated', models.DateTimeField(auto_now=True, verbose_name='is_updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('genre', models.CharField(max_length=100, verbose_name='genre')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
